name: chat_app_server_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  alfred: ^1.1.1
  zaptools_server: ^0.2.0-dev
# path: ^1.8.0
dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
